name: texmaker-amd64

on:
  workflow_dispatch:
    branch: master

jobs:
  build:
    name: 编译构建
    runs-on: ubuntu-latest
    container: linuxdeepin/deepin:crimson-amd64-v1.6.0

    steps:
    - name: 检查代码
      uses: actions/checkout@v4

    - name: 解压
      run: |
        apt update && apt upgrade -y
        apt install -y bzip2
        tar -xjvf texmaker-6.0.2.tar.bz2

    - name: 安装所需依赖
      run: |
        apt install -y build-essential cmake make git python3-pip qt6-base-dev qt6-5compat-dev \
          qt6-declarative-dev qt6-tools-dev qt6-tools-dev-tools qt6-webengine-dev libxcb-cursor0
        
        
    - name: 构建
      continue-on-error: false
      run: |
        cd texmaker-6.0.2
        ls
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build build -j 8

    - name: 清理构建产物


    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: texmaker-amd64
        path: ./build
